services:
  postgres_local:
    image: postgres:15-alpine
    container_name: gb_one_postgres_local
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: alya
    ports:
      - "5432:5432"
    networks:
      - alya_network

  backend:
    build: ./backend
    container_name: alya_backend
    ports:
      - "3000:3000"
    depends_on:
      - postgres_local
    networks:
      - alya_network

  frontend:
    build: ./frontend
    container_name: alya_frontend
    ports:
      - "8080:80"
    
    networks:
      - alya_network

networks:
  alya_network: